title: Nimal Danyath K - Portfolio
description: Personal Portfolio
url: "https://yourusername.github.io"  # Replace with your GitHub Pages URL
theme: jekyll-theme-cayman
highlighter: rouge
twitter_username: "nimaldanyathk"
github_username: "nimaldanyathk"

author:
  name: "Nimal Danyath K"
  email: "cb.sc.u4cse24033@cb.students.amrita.edu"
  avatar: "assets/images/profile.jpg"  # Update with your profile image path

social_links:
  - { name: "GitHub", url: "https://github.com/nimaldanyathk" }
  - { name: "LinkedIn", url: "https://linkedin.com/in/nimaldanyathk" }

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      author: "Nimal Danyath K"
